<?php

namespace AppBundle\Repository;

/**
 * RecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * [getIndexPageData [抓取帳單紀錄]
     * @return [query] [分頁功能所要query]
     */
    public function getIndexPageData()
    {
        $getIndexPageData = $this->createQueryBuilder('Record')->orderBy('Record.id', 'DESC');

        return $getIndexPageData;
    }
}
